name: Quality Assurance CI

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  qa:
    name: Quality Assurance CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Set up Python
        uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v6.0.0
        with:
          python-version-file: ".python-version"

      - name: Install Task
        uses: go-task/setup-task@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v1.0.0
        with:
          version: 3.x

      - name: Install uv
        uses: astral-sh/setup-uv@3259c6206f993105e3a61b142c2d97bf4b9ef83d # v7.1.0
        with:
          version: "0.9.3"
          enable-cache: true
          cache-dependency-glob: "uv.lock"

      - name: Clean
        run: task clean

      - name: Create or update docs/requirements.txt
        run: docs:requirements-txt

      - name: Install project
        run: task ci:install

      - name: Run formatter & linter
        run: task lint

      - name: Run type checker
        run: task typing

      - name: Tests docs build
        run: task docs:test

      - name: Tests tests and export coverage
        run: task ci:test
